experiment_name: Retrain_with_17_V1_New_rand_MM_SEC_4_drop_02_stm_10_CV_05_1_1
dataset_name: voxceleb2hq_pairs
dataset_name_test: voxceleb2hq_pairs
num_source_frames: 1
num_target_frames: 1
num_gpus: 8
batch_size: 2
test_batch_size: 4
max_epochs: 400
latent_dim: 512
image_size: 512
aug_warp_size: 512
use_amp_autocast: false
use_amp: false
model_checkpoint: true  # Set to true to enable checkpoint loading
random_seed: 42
check_grads_of_every_loss: false
logging_freq: 10
visuals_freq: 200
train_epoch_len: 15000
test_epoch_len: 2000
checkpoint_freq: 10

project_dir: "./"
background_net_input_channels: 64
norm_layer_type: 'gn'
norm_layer_type_3d: 'bn_3d'
estimate_head_pose_from_keypoints: true
head_pose_regressor_path: 'repos/head_pose_regressor.pth'
additive_motion: false
use_seg: true
use_back: false
features_sigm: 1
use_mix_mask: true
use_ibug_mask: false
use_old_fp: false
use_masked_aug: false
resize_depth: false
volume_renderer_mode: 'depth_to_channels'
save_exp_vectors: true
aligned_warp_rot_source: false
aligned_warp_rot_target: false
use_right_3d_trans: false
use_unet_as_s_nw: false
separate_stm: true
init_type: 'kaiming'
init_gain: 0.0
sep_vol_loss_scale: 0.0
bs_resnet18_fv_mix: 2

# Discriminator settings
dis_num_channels: 64
dis_max_channels: 512
dis_num_blocks: 4
dis_num_scales: 2
use_mix_dis: false
dis2_num_channels: 64
dis2_max_channels: 512
dis2_num_blocks: 4
dis2_num_scales: 2
dis2_train_start: 0
dis2_gen_train_start: 0
dis2_gen_train_ratio: 0
dis_init_type: 'xavier'
dis_init_gain: 0.02
dis_stylegan_lr: 0.0002

# Loss weights
adversarial: 1.0
mix_gen_adversarial: 1.0
feature_matching_weight: 40.0
vgg19_weight: 18
vgg19_neutral: 0.0
vgg19_neu_epoches: 0
vgg19_face: 10
perc_face_pars: 0
vgg19_face_mixing: 0.0
vgg19_fv_mix: 0.0
resnet18_fv_mix: 35
mix_losses_start: 1
contr_losses_start: 1
w_eyes_loss_l1: 500
w_mouth_loss_l1: 500
w_ears_loss_l1: 500
face_resnet: 0
vgg19_emotions: 0.0
resnet18_emotions: 0.0
landmarks: 0.0
l1_weight: 0.0
neu_exp_l1: 0.0
l1_back: 0.0
cycle_idn: 0.0
cycle_exp: 0.0
vgg19_cycle_idn: 0.0
vgg19_weight_cycle_idn: 0.0
vgg19_face_cycle_idn: 0.0
vgg19_cycle_exp: 0.0
vgg19_weight_cycle_exp: 0.0
vgg19_face_cycle_exp: 0.0
l1_vol_rgb: 0.0
l1_vol_rgb_mix: 0.0
volumes_l1: 0.5
stm: 10.0
pull_idt: 0.0
pull_exp: 1.0
volumes_pull: 0.0
volumes_push: 0.0
push_idt: 0.0
push_exp: 1.0
contrastive_exp: 2.0
contrastive_idt: 0.0
stylegan_weight: 1.0
neutral_expr_l1_weight: 0.0
r1: 2.0

# Model configuration
only_cycle_embed: true
detach_warp_mixing_embed: true
detach_dis_inputs: false
unet_first: false
use_mix_losses: true
pred_cycle: false
expr_custom_w: false
detach_cv_l1: false
gaze_weight: 10
vgg19_num_scales: 4
warping_reg: 0.0

# Network settings
spn_networks: 'local_encoder_nw, local_encoder_seg_nw, local_encoder_mask_nw, idt_embedder_nw, expression_embedder_nw, xy_generator_nw, uv_generator_nw, warp_embed_head_orig_nw, pose_embed_decode_nw, pose_embed_code_nw, volume_process_nw, volume_source_nw, volume_pred_nw, decoder_nw, backgroung_adding_nw, background_process_nw'
ws_networks: 'local_encoder_nw, local_encoder_seg_nw, local_encoder_mask_nw, idt_embedder_nw, expression_embedder_nw, xy_generator_nw, uv_generator_nw, warp_embed_head_orig_nw, pose_embed_decode_nw, pose_embed_code_nw, volume_process_nw, volume_source_nw, volume_pred_nw, decoder_nw, backgroung_adding_nw, background_process_nw'
spn_layers: 'conv2d, conv3d, linear, conv2d_ws, conv3d_ws'
use_sn: true
use_ws: true
print_norms: true
print_model: false

# Encoder/Generator settings
local_encoder_input_size: 3
no_channel_increase_3d_source: true
no_channel_increase_3d_pred: true
max_channel_res_3d_mul: 4
face_parts_epoch_start: 10
gen_opt_type: 'adamw'
gen_lr: 0.0002
gen_beta1: 0.5
gen_beta2: 0.999
gen_weight_decay: 0.0001
gen_weight_decay_layers: 'conv2d'
gen_weight_decay_params: 'weight'
grid_sample_padding_mode: 'zeros'
gen_shd_type: 'cosine'
gen_shd_max_iters: 400000
gen_shd_lr_min: 1e-6
dis_opt_type: 'adamw'
dis_lr: 0.0002
dis_beta1: 0.5
dis_beta2: 0.999
dis_input_channels: 3
dis_shd_type: 'cosine'
dis_shd_max_iters: 400000
dis_shd_lr_min: 4e-6
eps: 1e-8
gen_num_channels: 32
gen_max_channels: 512
dec_max_channels: 512
dec_no_detach_frec: 1
dec_key_emb: 'orig_d'
gen_max_channels_unet3d: 512
gen_max_channels_loc_enc: 512
gen_activation_type: 'relu'
gen_downsampling_type: 'avgpool'
gen_upsampling_type: 'trilinear'
gen_pred_flip: false
gen_pred_mixing: true
less_em: false
cat_em: false
volume_rendering: false
vol_renderer_dec_channels: '96*16'
predict_target_canon_vol: true
type_of_can_vol_loss: 'l1'
vol_loss_epoch: 1
vol_loss_grad: 1


use_modnet_mask: true

# Image and volume settings
idt_image_size: 256
exp_image_size: 256
image_additional_size: null
gen_latent_texture_size: 64
gen_latent_texture_depth: 16
gen_latent_texture_channels: 96
latent_volume_channels: 96
latent_volume_size: 64
latent_volume_depth: 16
source_volume_num_blocks: 3
pred_volume_num_blocks: 0

# Additional settings
use_tensor: false
old_mix_pose: false
green: true
random_theta: true
emb_v_exp: false
use_smart_scale: false
smart_scale_max_scale: 0.75
smart_scale_max_tol_angle: 0.8
reduce_em_ratio: 2
gen_embed_size: 4
gen_dummy_input_size: 8
gen_use_adanorm: false
gen_use_adaconv: false
gen_adaptive_conv_type: 'sum'
gen_adaptive_kernel: false
sep_test_losses: true
gen_adaptive_use_annealing: false
gen_adaptive_annealing_type: 'cos'
gen_adaptive_annealing_max_iter: 100000
warp_block_type: 'res'
warp_channel_mult: 1.0
warp_norm_grad: false
warp_output_size: 64
enc_init_num_channels: 512
enc_channel_mult: 4.0
enc_block_type: 'res'
tex_use_skip_resblock: true
tex_pred_rgb: false
dec_use_adanorm: false
dec_use_adaconv: false
dec_use_sg3_img_dec: false
dec_num_blocks: 6
dec_channel_mult: 2.0
dec_up_block_type: 'res'
dec_pred_seg: false
dec_seg_channel_mult: 1.0
im_dec_num_lrs_per_resolution: 2
im_dec_ch_div_factor: 1.5
dec_pred_conf: false
dec_bigger: false
sep_train_losses: false
dec_conf_ms_names: 'target_vgg19_conf, target_fem_conf'
dec_conf_names: ''
dec_conf_ms_scales: 5
dec_conf_channel_mult: 1.0
separate_idt: false
idt_backbone: 'resnet50'
idt_lr_mult: 1.0
idt_output_channels: 512
idt_output_size: 4
lpe_head_backbone: 'resnet18'
lpe_face_backbone: 'resnet18'
lpe_lr_mult: 1.0
lpe_final_pooling_type: 'avg'
lpe_output_channels: 512
lpe_output_channels_expression: 128
exp_dropout: 0.2
lpe_output_size: 4
lpe_head_transform_sep_scales: false
num_b_negs: 1
use_stylegan_d: false
barlow: 0.0

# Additional training settings
normalize_losses: true
custom_test: true
augment_geometric_train: false
sec_dataset_every: 4
detach_lat_vol: -1
aug_color_coef: 10
use_sec_dataset: true

warping_reg_weight: 0.0
adversarial_weight:  1.0
# mix_gen_adversarial: float = 1.0
# feature_matching_weight:  40.0
# vgg19_weight: 20.0

# gaze_weight: 10.0


amp_opt_level: 'O0'
augment_color_train: True
coarse_num_sample: 48
d_reg_every: 16
data_root: '/fsx/VC2_HD_f'
dataset_name_mead: 'mead_faces_pairs'
dataset_name_sec: 'extrime_faces_pairs'
dataset_name_test_mead: 'mead_faces_pairs'
dataset_name_test_sec: 'extrime_faces_pairs'
entity: 'animator'
freeze_proc_nw: -1.0
gray_source_prob: 0.0
hidden_vol_dec_dim: 448
image_additional_size_d: 'None'
latest_checkpoint_freq: 1
local_rank: 'None'
log_wandb: True
match_neutral: False
mead_as_second_every: 0
model_name: 'va'
model_type: 'volumetric_avatar'
num_layers_vol_dec: 2
num_workers: 16
output_aug_warp: True
output_aug_warp_out: True
output_visuals: True
project_name: 'main_gig'
rand_crop_prob: 0.0
rand_crop_scale: 0.9
rand_shift_prob: 0.0
rot_aug_angle: 0.0
scale_cond_tr: 0.8
shift_limit: 0.1
squeeze_dim: 0
start_vol_rgb: 0
targ_vol_loss_scale: 0.0
test_freq: 1
trainer_checkpoint: 'None'
use_diverse: True
use_hq: True
use_torch_ddp: False
warp_aug_color_coef: 1.0